server:
  port: 8088
spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        # primary: master 指定的master 就是下面的这个 也就是他就是默认的数据源
        master:
          url: jdbc:mysql://bj-cynosdbmysql-grp-jjeu6agm.sql.tencentcdb.com:26555/us
          username: root
          password: Qq1574581952
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://bj-cynosdbmysql-grp-jjeu6agm.sql.tencentcdb.com:26555/us1
          username: root
          password: Qq1574581952
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_2:
          url: jdbc:mysql://bj-cynosdbmysql-grp-jjeu6agm.sql.tencentcdb.com:26555/us2
          username: root
          password: Qq1574581952
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_uk:
          url: jdbc:mysql://bj-cynosdbmysql-grp-jjeu6agm.sql.tencentcdb.com:26555/uk
          username: root
          password: Qq1574581952
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_jp:
          url: jdbc:mysql://bj-cynosdbmysql-grp-jjeu6agm.sql.tencentcdb.com:26555/jp
          username: root
          password: Qq1574581952
          driver-class-name: com.mysql.cj.jdbc.Driver
# MyBatis Plus配置
mybatis-plus:
  #配置日志  打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*.xml



#公众号配置
wechat:
  appId: wxfb5df9c22d703391
  appSecret: d929c5b254e961b1d952499e5af3ff81
  tempId: jZdbxabaxDpKSkaODu-ksA1jT5Z2bChLgVmlUxpeJys
  tempIdW: dBMhQOLZg6SpJhM5ko2wN4II5tI-W0K6QySeiaYkwlk
  myBirthday: 2023-04-17
  babyBirthday: 2000-04-17
  loveDay: 2000-04-17
  tempIdHs: JNAi0z0f9elu_2IgxmzU8IlnSAi0ZeO_c8LMDhxdmL4

#彩虹屁接口
tianapi:
  appKey: 751a876c86952fde6d27e9d13c62da17
  area: 昌平
